name: untitled1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  nb_utils: ^7.0.7
  path_provider: ^2.1.5
  csv: ^6.0.0
  image_picker: ^1.1.2
  flutter_otp_text_field: ^1.2.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.7
  speech_to_text: ^7.0.0
  flutter_local_notifications: ^18.0.1
  pdf: ^3.11.1
  fl_chart: ^0.69.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
    - family: playFair_Display
      fonts:
        - asset: assets/fonts/playFair_Display/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/playFair_Display/PlayfairDisplay-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true

